### ISSUE TITLE
Running with different version of OpenMPI

### ISSUE THREAD

**Issue by camilo1729** [cea-hpc/wi4mpi#1]
Hello 

I'm performing some tests with the library and the conversion OpenMPI -> IntelMPI and IntelMPI-> OpenMPI worked without problem. When I try between different versions of OpenMPI: 1.8.3, 1.10.4 and 2.01 I was able to run a new version (2.01) with an old version (1.8.3 or 1.10.4) but not the other way around.  When I try to run an old version with a new implementation I always got a Segmentation fault. For example, when I have a binary compiled with 1.8.3 and I try to run  it with 1.10.4: 

export WI4MPI_INTERNAL_INCLUDES=/home/cruiz/software/wi4mpi/INTERNAL/include/
export TRUE_MPI_LIB=/opt/openmpi-1.10.4/lib/x86_64-linux-gnu/libmpi.so
export TRUE_MPI_F_LIB=/opt/openmpi-1.10.4/lib/x86_64-linux-gnu/libmpi_mpifh.so
export LD_LIBRARY_PATH="/home/cruiz/software/wi4mpi/libexec/wi4mpi/fakelibCXX/:$LD_LIBRARY_PATH"
export LD_PRELOAD="/home/cruiz/software/wi4mpi/libexec/wi4mpi/libwi4mpi_OMPI_OMPI.so $TRUE_MPI_F_LIB $TRUE_MPI_LIB"
export WI4MPI_APP_INCLUDES=/home/cruiz/software/wi4mpi/INTERNAL/preload/include/OMPI_OMPI
export WI4MPI_COMPILE_OPT="-Dompi_mpich -DOMPI_OMPI"

 mpirun -np 8 cg.C.8-openmpi-1.8.2
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 19345 on node eogn0007 exited on signal 11 (Segmentation fault).

Is this normal behavior?
Thanks in advance

**Comment by frogeb** [comment]
Hello Cristian,
we try to reproduced the issue without succes. With this version of wi4mpi 3.0.4, the conversion from ompi-2.0.1 to ompi-1.8.8 and conversion from ompi-1.8.8 to ompi-2.0.1 work well.
Since, the code has been updated, could you retry your test with the latest version (3.1.4)
Normally, the wi4mpi library must support this kind of conversion, except for the very old version of ompi (before 1.8.8)

**Comment by marcjoos-cea** [comment]
This issue should have been fixed and is no longer valid. Please reopen the issue is the problem reappears.
