### ISSUE TITLE
Using interface version

### ISSUE THREAD

**Issue by camilo1729** [cea-hpc/wi4mpi#2]
Hello

I compiled the library to use the interface version and I succeeded to compile a parallel application using the mpif90 available in the wi4mpi path but the mpirun seems no to be implemented:

$ cat ~/software/wi4mpi-interface/bin/mpirun
echo "Needed to pass some configure"

Is this normal ? what is the procedure to run the application? 

Thank you in advance

**Comment by frogeb** [comment]
Hello Cristian,
the script ~/software/wi4mpi-interface/bin/mpirun is present to prevent some issues with installer like cmake.
Some installers test the avalability of kind of script.
To lunch your application , you must use the launcher of the targeted mpi librarie.
