### ISSUE TITLE
mpiexec not found

### ISSUE THREAD

**Issue by adrien-cotte** [cea-hpc/wi4mpi#26]
We should add `mpiexec`, symlink to `mpirun`, right?

**Comment by marcjoos-cea** [comment]
I would argue for a seperate `mpiexec` wrapper, as `mpiexec` is the standard (meaning defined in the MPI-3 norm) command whereas `mpirun` is a convenient ­-- but not standardized -- startup command (see 8.8 in MPI-3.1 norm).
