### ISSUE TITLE
Compilation fails due to possible source code syntax errors

### ISSUE THREAD

**Issue by gsamonds** [cea-hpc/wi4mpi#28]
When building version 3.6.0 using the example in the README, compilation fails with errors like:

```
[  5%] Building C object src/CMakeFiles/wi4mpi_MPICH_MPICH.dir/preload/gen/mpi_translation_c.c.o
In file included from /nishome/gsm/freeware_build/wi4mpi/src/common/mappers.h(137),
                 from /nishome/gsm/freeware_build/wi4mpi/src/preload/gen/mpi_translation_c.c(139):
/nishome/gsm/freeware_build/wi4mpi/src/preload/header/MPICH_MPICH/app_mpi.h(936): error: identifier "predefined" is undefined
                                           predefined error class */
                                           ^
```
Many more similar errors follow.  It looks as if there might be a comment character out of place somewhere, or that my compiler is not interpreting multi-line comments correctly.

I rolled back to 5294a6c and was then able to complete the build without issue.

**Comment by adrien-cotte** [comment]
Many thanks for your feedback, we gonna check!
@Clement-Fontenaille do you have any idea? Maybe the new generator?

**Comment by Clement-Fontenaille** [comment]
Hi ,
Thanks for your input !

We fixed a couple of errors. Can you retry using that new version ?

I am currently attempting to reproduce your error.
