### ISSUE TITLE
mpicc configure dlopen link error with ubuntu

### ISSUE THREAD

**Issue by adrien-cotte** [cea-hpc/wi4mpi#46]
On ubuntu, mpicc wrappers of mpich and openmpi have `-L/lib/x86_64-linux-gnu/ -ldl`.

Wi4MPI mpicc doesn't so osu-microbenchmark configure fails with `undefined reference to dlopen`.

The workaround is:

```
./configure CC=mpicc CXX=mpicxx LIBS="-L/lib/x86_64-linux-gnu/ -ldl"
```

We must add this knowledge inside the mpicc wrapper of Wi4MPI.

Maybe something like that?

```
# Ubuntu-like distributions have a specific path to libdl.so, this fix ./configure MPI detect
if [[ -e "/lib/x86_64-linux-gnu/libdl.so" ]]; then
    WI4MPI_LDFLAGS="${WI4MPI_LDFLAGS} -L/lib/x86_64-linux-gnu/ -ldl"
fi
```

**Comment by adrien-cotte** [comment]
Well, my initial post is wrong.

The real workaround is :

```
./configure CC=mpicc CXX=mpicxx LDFLAGS="-Wl,--no-as-needed"
```

It seems to be useful only in an Ubuntu Dockerfile.
Weird but not sure it is related to Wi4MPI.

Maybe we can close this issue.

**Comment by adrien-cotte** [comment]
Should be add in documentation.

**Comment by marcjoos-cea** [comment]
Documented in [Podman tutorial](https://github.com/cea-hpc/wi4mpi/blob/master/doc/source/tutorial/podman.rst) from c1862af
