### ISSUE TITLE
wi4mpi command doesn't work with different installations of MPI

### ISSUE THREAD

**Issue by laurent-nguyen** [cea-hpc/wi4mpi#48]
See with OpenMPI and IntelOneAPI, it seems [wi4mpi](https://github.com/cea-hpc/wi4mpi/blob/0925747a707275115009d357452be2843faba1e6/src/preload/bin/wi4mpi#L102) command set paths (with lib or lib64). But, the MP installations can be different along the way there are packaged (manually compiled or Fedora packaging for example).

I suggest to detect if `${MPI_ROOT}/lib/libmpi.so` does exist, otherwise try with `${MPI_ROOT}/lib64/libmpi.so`.

**Comment by adrien-cotte** [comment]
Obviously... Thanks for your feedback!

**Comment by kevin-juilly** [comment]
In Fedora (and other Red Hat related distribution), the lib64 is part of the prefix (/usr/lib64/openmpi).
If someone manually compiles an mpi and does not use ${MPI_ROOT}/lib, they probably overrided libdir at configure time. It means it can be anything so it's on them to properly export WI4MPI_RUN_* variables.

But I still did the work, refactoring the script as a bonus.
