### ISSUE TITLE
Unexpected returns from `MPI_Type_get_envelope` in interface mode

### ISSUE THREAD

**Issue by spoutn1k** [cea-hpc/wi4mpi#51]
Hello everyone,

I have been trying to build a GPU code (PETSc https://gitlab.com/petsc/petsc) using Wi4MPI in interface mode. The build went well, but I am getting an error at execution about the return values of `MPI_Type_get_envelope`:

In a gist for brevity:
https://gist.github.com/spoutn1k/34160841a22a818dc813e0531db3fcf5

It would seem the returned values are not what the program expects in:
https://gitlab.com/petsc/petsc/-/blob/main/src/vec/is/sf/interface/sftype.c#L48

I am planning to look further into it, but I wanted to create this issue to open the discussion on this issue, and not waste time if this is known behaviour.

**Comment by Clement-Fontenaille** [comment]
Hi JB,

thanks for bringing this up, I am attempting to reproduce this issue.
Can you provide the configure line used to compile petsc, as well as a test code that produces the error ?
