### ISSUE TITLE
Symbol size warning in preload mode, with OpenMPI as from family

### ISSUE THREAD

**Issue by kevin-juilly** [cea-hpc/wi4mpi#69]
```
Symbol `ompi_mpi_comm_null' has different size in shared object, consider re-linking
```
The size of the predefined communicators changed over time in openmpi.
Starting with v1.3.2, those got a fixed size based on a macro named `PREDEFINED_COMMUNICATOR_PAD`.
From v1.3.2 to v1.10.7 it was `(sizeof(void*) * 128)`.
In all versions 2.x.x, it was `(sizeof(void*) * 192)`.
In versions 3.0.x, it was `(sizeof(void*) * 64)`.
Since version 3.1.0, it is hard-coded as `512`.

In wi4mpi, we made them 1024 bytes long, which correspond to a 64 bit build of openmpi v1 since the pad exists.
This message can be ignored (we only care about the address of the symbol, not its size in preload mode) but it could worry users.

I propose to pass it to 512 bytes in wi4mpi, it should remove the warning.

Any disagreement?

**Comment by adrien-cotte** [comment]
Seems great to me, thx for looking into this old subject.
