### ISSUE TITLE
Error: could not find the C target mpi library - for both IntelMPI and mpich

### ISSUE THREAD

**Issue by cessenat** [cea-hpc/wi4mpi#9]
On Ubuntu 18.04.01 LTS I installed wi4mpi-3.4.0 and configured etc/wi4mpi.cfg with
INTELMPI_DEFAULT_ROOT="/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64"
MPICH_DEFAULT_ROOT="/opt/mpichclone"
 - mpich libs are located on /usr/lib/x86_64-linux-gnu and mpirun is a symlink to /etc/alternatives/mpirun so I copied what I thought was relevant to /opt/mpichclone
 - for Intel I had to symlink bin to bin64 since there is no bin64 and wi4pi demands it.
In both cases, I compiled with /opt/ompi182 which is OpenMPI 1.8.2 - that works well on all my platforms, iOS, Raspbian...
Then I get an error:
mpirun -np 2 -T intelmpi -F openmpi ./a.hello
Error: could not find the C target mpi library.
Error: could not find the C target mpi library.

**Comment by adrien-cotte** [comment]
Can you run with `VERBOSE=1`, please?

```
VERBOSE=1 mpirun -np 2 -T intelmpi -F openmpi ./a.hello
```

We need to understand why `WI4MPI_RUN_MPI_C_LIB` is not auto-detected.

**Comment by cessenat** [comment]
It still does not indicate anything else than
```
Error: could not find the C target mpi library.
Error: could not find the C target mpi library.
```

**Comment by adrien-cotte** [comment]
Well... I open this verbosity issue in #15...
Let's focus on yours :-)

Can you try this?

```
wi4mpi -v -f openmpi -t intelmpi ./a.hello
```

**Comment by cessenat** [comment]
$ wi4mpi -v -f openmpi -t intelmpi  /opt/wi4mpi-3.4.0/bin/a.hiall
```
PRELOAD MODE
Error: could not find the C target mpi library.
```

**Comment by adrien-cotte** [comment]
Hi @cessenat !
Should we close this issue or are you still facing problems with wi4mpi?
Best,
Adrien

**Comment by cessenat** [comment]
Well, from that time I changed to Ubuntu 20.
I tried v3.6.2 with mpich, it fails:
```
$ mpirun -np 2 -T intelmpi -F mpich /tmp/a.hello
[mpiexec@jliana] match_arg (../../../../../src/pm/i_hydra/libhydra/arg/hydra_arg.c:91): unrecognized argument T
[mpiexec@jliana] Similar arguments:
[mpiexec@jliana] 	 V
[mpiexec@jliana] 	 s
[mpiexec@jliana] 	 n
[mpiexec@jliana] 	 h
[mpiexec@jliana] 	 f
[mpiexec@jliana] HYD_arg_parse_array (../../../../../src/pm/i_hydra/libhydra/arg/hydra_arg.c:128): argument matching returned error
[mpiexec@jliana] mpiexec_get_parameters (../../../../../src/pm/i_hydra/mpiexec/mpiexec_params.c:1338): error parsing input array
[mpiexec@jliana] main (../../../../../src/pm/i_hydra/mpiexec/mpiexec.c:1738): error parsing parameters
```
My etc/wi4mmpi.cfg is
```
#This part is handled by cmake
WI4MPI_VERSION="3.6.2"
#Please provide the following variables to use the launcher
OPENMPI_DEFAULT_ROOT=""
INTELMPI_DEFAULT_ROOT="/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64"
MPC_DEFAULT_ROOT=""
MPICH_DEFAULT_ROOT="/usr"

```

**Comment by spoutn1k** [comment]
What is the output of `which mpirun` ? It looks like you are not using `wi4mpi`'s launcher.

**Comment by cessenat** [comment]
Indeed ; corecting:
```
$ WI4MPI_ROOT=/home/cessenat/opt/wi4mpi ~/opt/wi4mpi/bin/mpirun -n 2 -T intelmpi -F mpich /tmp/a.hello
[proxy:0:0@jliana] HYD_spawn (../../../../../src/pm/i_hydra/libhydra/spawn/intel/hydra_spawn.c:145): execvp error on file wi4mpi (No such file or directory)
[proxy:0:0@jliana] HYD_spawn (../../../../../src/pm/i_hydra/libhydra/spawn/intel/hydra_spawn.c:145): execvp error on file wi4mpi (No such file or directory)
$ ll /tmp/a.hello
-rwxr-xr-x 1 cessenat users 17000 sept. 28 17:52 /tmp/a.hello*
```

**Comment by spoutn1k** [comment]
This is also a `PATH` issue, for some reason the `wi4mpi` binary is not found. It is located in the `bin` folder of your Wi4MPI installation.

```
PATH=$HOME/opt/wi4mpi/bin:$PATH WI4MPI_ROOT=/home/cessenat/opt/wi4mpi mpirun -n 2 -T intelmpi -F mpich /tmp/a.hello
```

**Comment by cessenat** [comment]
```
$ PATH=$HOME/opt/wi4mpi/bin:$PATH WI4MPI_ROOT=/home/cessenat/opt/wi4mpi mpirun -n 2 -T intelmpi -F mpich /tmp/a.hello
Error: could not find the C target mpi library. You might want to set WI4MPI_RUN_MPI_C_LIB such as /path/to/libmpi.so
Error: could not find the C target mpi library. You might want to set WI4MPI_RUN_MPI_C_LIB such as /path/to/libmpi.so
```

**Comment by ocaisa** [comment]
You are missing the path in your `LD_LIBRARY_PATH` so it can find the library. Since you set WI4MPI_ROOT I think it would be good if `mpiexec` was able to do this for you.

**Comment by ocaisa** [comment]
The alternative would to use wi4mpi via an environment module which sets these variables for you

**Comment by adrien-cotte** [comment]
Maybe the new tutorial could be a good (re)start, you can build the new doc with Sphinx as indicated in README since Wi4MPI 3.6.2 release.
Or just look at file `doc/source/tutorial.rst`.
Moreover, there is a new file to help env setting : `share/wi4mpi/setup-env.sh`.
Sourcing it could help too.

**Comment by cessenat** [comment]
> doc/source/tutorial.rst

I did not find doc/source/tutorial.rst ;  source share/wi4mpi/setup-env.sh and same message.
I'm confused.
Is there a better platform than Ubuntu for testing that you could reckon ?

**Comment by marcjoos-cea** [comment]
Which version are you using? The documentation was updated this week with the 3.6.2 release. You can of course also read it online:
https://github.com/cea-hpc/wi4mpi/blob/master/doc/source/tutorial.rst

**Comment by cessenat** [comment]
I'm using 3.6.2.
I did the tuto ; it worked (thanks spack !)
Then I applied to my code : from mpich to openmpi ; it worked.
Remains to apply with intelmpi ; keep in touch.

**Comment by cessenat** [comment]
From a fresh window 
```
$ which mpirun
/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/bin/mpirun
spack unload -a
#spack load openmpi
spack load wi4mpi
mpirun -F mpich -T intelmpi -n 2 /tmp/a.hello
Error: could not find the C target mpi library. You might want to set WI4MPI_RUN_MPI_C_LIB such as /path/to/libmpi.so
Error: could not find the C target mpi library. You might want to set WI4MPI_RUN_MPI_C_LIB such as /path/to/libmpi.so
```
Here is my cfg:
```
#This part is handled by cmake
WI4MPI_VERSION="3.6.0"
#Please provide the following variables to use the launcher
INTELMPI_DEFAULT_ROOT="/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64"
MPC_DEFAULT_ROOT=""
MPICH_DEFAULT_ROOT="/opt/spack/linux-ubuntu20.04-zen2/intel-2021.5.0/mpich-4.0.2-argivh6nvlbx4bbphkg7u6anpzbbtwfd"
OPENMPI_DEFAULT_ROOT="/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/openmpi-4.1.4-6gf6dg5kecboiiotzuoq7oflpyxcd6gz"

```
Going further, put intel-mpi into spack as external:
```
  intel-mpi:
    externals:
    - spec: intel-mpi@19.1.3.304
      prefix: /opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64

```
then using spack I got the same message. Probably my Intel-mpi installation is not correct.
We may close this issue.
